// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ProgressContext))]
    [Migration("20250910024549_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ProblemStats", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AvgPoint")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubmisstion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ProblemStats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgPoint = 9,
                            TotalSubmisstion = 1
                        },
                        new
                        {
                            Id = 2,
                            AvgPoint = 3,
                            TotalSubmisstion = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmisstionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Submission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Language = "c sharp",
                            Point = 9,
                            ProblemId = 1,
                            SubmisstionAt = new DateTime(2025, 9, 10, 9, 45, 48, 800, DateTimeKind.Local).AddTicks(4378),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserProgress", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("EasySolved")
                        .HasColumnType("int");

                    b.Property<int>("HardSolved")
                        .HasColumnType("int");

                    b.Property<int>("MediumSolved")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubmisstion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserProgress", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EasySolved = 1,
                            HardSolved = 0,
                            MediumSolved = 0,
                            Rank = 900,
                            TotalSubmisstion = 1
                        },
                        new
                        {
                            Id = 2,
                            EasySolved = 1,
                            HardSolved = 0,
                            MediumSolved = 0,
                            Rank = 1,
                            TotalSubmisstion = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Submission", b =>
                {
                    b.OwnsOne("Domain.ValueEntities.EvaluationCriteria", "EvaluationCriteria", b1 =>
                        {
                            b1.Property<int>("SubmissionId")
                                .HasColumnType("int");

                            b1.Property<string>("Algorithm")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Algorithm");

                            b1.Property<string>("CleanCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CleanCode");

                            b1.HasKey("SubmissionId");

                            b1.ToTable("Submission");

                            b1.WithOwner()
                                .HasForeignKey("SubmissionId");

                            b1.HasData(
                                new
                                {
                                    SubmissionId = 1,
                                    Algorithm = "Algorithm is correct and efficient for the given task. No issues detected.",
                                    CleanCode = "Code is readable and follows basic C++ conventions. Could benefit from comments for clarity."
                                },
                                new
                                {
                                    SubmissionId = 2,
                                    Algorithm = "Algorithm is correct and efficient for the given task. No issues detected.",
                                    CleanCode = "Code is readable and follows basic C++ conventions. Could benefit from comments for clarity."
                                });
                        });

                    b.Navigation("EvaluationCriteria")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
